# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "deploy-rs"
name = "deploy"
help = "deploy Nix anywhere"

[[commands]]
name = "access_keys_from_csv"
command = "${PRJ_ROOT}/scripts/access_keys_from_csv.sh"
help = "credential process helper for aws"
category = "helpers"

[[commands]]
name = "tag_and_push_lambda"
command = "${PRJ_ROOT}/scripts/tag_and_push_lambda.sh"
help = "credential process helper for aws"
category = "helpers"

[[commands]]
package = "docker"

[[env]]
name = "AWS_USERNAME"
eval = "$(whoami)"

# for terraform
[[env]]
name = "TF_VAR_prj_root"
eval = "$PRJ_ROOT"

[devshell]
name = "nix-party-tricks"

packages = [
  "awscli2",
  "terraform",
  "git",
]
